#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""从 NapCat 的 face_config.json 生成 QqFaceCatalog.cs（QQ 原生小表情 id → 中文名）。

为什么用这个数据源：它是协议端自己（NapCat）的厂商数据，QSid 就是 OneBot face 段的 id，
QDes 就是 QQ 里的名字（/微笑、/捂脸…），同时覆盖经典表情（0..244）和新版系统表情（260+）。
手抄或凭记忆写三百个名字迟早出错，所以做成生成脚本 —— 数据更新时重跑即可。

用法：
    curl -sLO https://raw.githubusercontent.com/NapNeko/NapCatQQ/main/packages/napcat-core/external/face_config.json
    python tools/gen_face_catalog.py face_config.json src/QQChatAgent.Headless/Services/OneBot/QqFaceCatalog.cs
"""
import io
import json
import sys

SRC = sys.argv[1] if len(sys.argv) > 1 else 'face_config.json'
OUT = sys.argv[2] if len(sys.argv) > 2 else 'src/QQChatAgent.Headless/Services/OneBot/QqFaceCatalog.cs'

data = json.load(io.open(SRC, encoding='utf-8'))
pairs = {}
for item in data.get('sysface', []):
    qsid = str(item.get('QSid', '')).strip()
    des = str(item.get('QDes', '')).strip()
    if not qsid.isdigit() or not des:
        continue
    name = des.lstrip('/').strip()
    if name:
        pairs[int(qsid)] = name

if not pairs:
    raise SystemExit('没解析到任何表情，检查数据源')

lines = [
    '// <auto-generated>',
    '//     由 NapCat 的 face_config.json（sysface 段）生成：QSid = OneBot face 段 id，QDes = 名字。',
    '//     数据源 https://github.com/NapNeko/NapCatQQ/blob/main/packages/napcat-core/external/face_config.json',
    '//     重新生成：python tools/gen_face_catalog.py（别手改本文件，改脚本）',
    '// </auto-generated>',
    '#nullable enable',
    '',
    'namespace QQChatAgent.Services.OneBot;',
    '',
    '/// <summary>QQ 原生小表情 id → 中文名（经典表情 0..244 与新版系统表情 260+ 都在内）。</summary>',
    'public static class QqFaceCatalog',
    '{',
    '    private static readonly Dictionary<int, string> Names = new()',
    '    {',
]
for fid in sorted(pairs):
    lines.append(f'        [{fid}] = "{pairs[fid]}",')
lines += [
    '    };',
    '',
    '    /// <summary>查名字；查不到返回 null（调用方用 id 兜底显示，别猜名字）。</summary>',
    '    public static string? Name(int id) => Names.TryGetValue(id, out var name) ? name : null;',
    '',
    '    /// <summary>把消息段里的表情 id 文本转成“可读名字”，认不出来就如实写成 未知(id)。</summary>',
    '    public static string Describe(string? rawId)',
    '    {',
    '        if (string.IsNullOrWhiteSpace(rawId))',
    '        {',
    '            return "表情";',
    '        }',
    '',
    '        return int.TryParse(rawId.Trim(), out var id) && Name(id) is { } name',
    '            ? name',
    '            : $"未知({rawId.Trim()})";',
    '    }',
    '}',
]
io.open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
print(f'已写出 {OUT}：{len(pairs)} 个表情，id {min(pairs)}..{max(pairs)}')
